# Generated by Django 3.2.2 on 2021-05-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sghouse', '0003_content_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.FileField(blank=True, upload_to='documents/%Y.%m'),
        ),
    ]
